language: rust

rust:
  #- stable ## Let's spare Travis
 - nightly

before_install:
 - wget https://code.videolan.org/videolan/dav1d/-/archive/0.1.0/dav1d-0.1.0.tar.gz
 - tar dav1d-0.1.0.tar.gz
 - git submodule update --init --recursive

script: 
 - cargo build --release --verbose
 - cargo test --verbose
